"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { inviteAdminUser, removeAdminUser, updateAdminUserRole } from "../app/actions/admin-users";
import type { Profile, UserRole } from "../lib/supabase/types";
import { Hint } from "./studio-hint";

const roles: UserRole[] = ["owner", "admin", "developer", "staff"];
export default function UsersAdmin({ initialUsers }: { initialUsers: Array<Pick<Profile, "id" | "email" | "full_name" | "role" | "created_at">> }) {
  const router = useRouter();
  const [users, setUsers] = useState(initialUsers); const [email, setEmail] = useState(""); const [role, setRole] = useState<UserRole>("admin"); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => setUsers(initialUsers), [initialUsers]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); const result = await inviteAdminUser(email, role); if (!result.ok) setError(result.error ?? "Could not send invitation."); else { setMessage(`Invitation sent to ${email}.`); setUsers((current) => current.filter((item) => item.id !== `pending-${email}`)); setEmail(""); router.refresh(); } setBusy(false); }
  async function changeRole(user: typeof users[number], nextRole: UserRole) { const result = await updateAdminUserRole(user.id, nextRole); if (!result.ok) setError(result.error ?? "Could not update that role."); else { setUsers((current) => current.map((item) => item.id === user.id ? { ...item, role: nextRole } : item)); setMessage(`Role updated for ${user.email ?? "user"}.`); } }
  async function removeUser(user: typeof users[number]) { if (user.id.startsWith("pending-") || !window.confirm(`Remove ${user.email ?? "this user"} from the studio? This also deletes their Supabase sign-in.`)) return; const result = await removeAdminUser(user.id); if (!result.ok) setError(result.error ?? "Could not remove that user."); else { setUsers((current) => current.filter((item) => item.id !== user.id)); setMessage(`Removed ${user.email ?? "user"}.`); } }
  return <section className="admin-user-section"><form className="admin-operation-form admin-invite-form" onSubmit={submit}><Hint id="invite"><h2>Invite a user</h2></Hint><Hint id="loginEmail"><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label></Hint><Hint id="role"><label>Role<select value={role} onChange={(event) => setRole(event.target.value as UserRole)}>{roles.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></Hint><p className="admin-form-note">The invitee sets their own password from the secure Supabase link.</p>{error && <p className="admin-error" role="alert">{error}</p>}{message && <p className="admin-inline-success" role="status">{message}</p>}<Hint id="sendInvite"><button className="admin-action-button" disabled={busy} type="submit"><span className="admin-action-label">{busy ? "Inviting…" : "Invite by email"}</span></button></Hint></form><div className="admin-user-list">{users.map((user) => <article className="admin-user-card" key={user.id}><div><strong>{user.full_name || user.email || "Unnamed user"}</strong><span>{user.email}</span></div><div className="admin-card-actions">{!user.id.startsWith("pending-") && <Hint id="role"><select aria-label={`Role for ${user.email ?? "user"}`} value={roles.includes(user.role) ? user.role : "admin"} onChange={(event) => void changeRole(user, event.target.value as UserRole)}>{roles.map((item) => <option key={item} value={item}>{item}</option>)}</select></Hint>}{!user.id.startsWith("pending-") && <Hint id="removeUser"><button className="admin-small-button admin-danger-button" onClick={() => void removeUser(user)} type="button">Remove</button></Hint>}</div></article>)}</div></section>;
}
