export const studioHints = {
  wordmark: "Back to your Studio overview.",
  navCatalogue: "Add, edit, and arrange your artworks — these are the pieces shown in your public shop.",
  navInquiries: "Messages from people interested in a specific piece or a commission.",
  navSales: "Record a sale to mark a piece sold and build your revenue history.",
  navCustomers: "Everyone who's bought or enquired, with their history in one place.",
  navScheduling: "Block off dates you're unavailable and log consultations.",
  navUsers: "Invite teammates and control who can access the Studio.",
  navInsights: "Your numbers — revenue, best sellers, and repeat buyers.",
  navSettings: "Switch on upgrade features (payments, booking) when you're ready.",
  navSystems: "See grouped Studio errors and their recent occurrences.",
  viewSite: "Open your public website to see what visitors see.",
  signOut: "Securely log out of the Studio.",
  userRole: "You're signed in here — the tag shows your access level.",
  tips: "Turn these little hints on or off anytime.",
  addWork: "Start a new piece — add its photos, details, and price.",
  statusFilters: "Show or hide pieces by status. Drafts are only visible here, never in the shop.",
  catalogueSearch: "Find a piece by title, series, slug, medium, or year.",
  clearSearch: "Clear the catalogue search.",
  seriesFilter: "Show only pieces assigned to this collection.",
  quickAdd: "Rapidly create several placeholder pieces to flesh out later.",
  bulkStatus: "Change the status of every selected piece at once.",
  bulkSeries: "Move all selected pieces into a collection.",
  createSeries: "Create a new collection and assign it to every selected piece.",
  applyBulk: "Apply the chosen bulk change to your selected pieces.",
  applyDetails: "Apply the filled-in details to every selected piece. Blank fields stay unchanged.",
  selectAll: "Select or clear every piece currently shown by the search and filters.",
  saveSelected: "Save the edited names and prices for the selected pieces.",
  rowStatus: "Change this piece's catalogue status immediately.",
  viewWork: "Open this piece to edit its details or photos.",
  title: "The name of the piece (required).",
  slug: "The piece's web address — auto-fills from the title; edit only if you want.",
  year: "Year created (required) — used to group your catalogue.",
  series: "Put the piece in a collection, or type a new name to create one on the spot.",
  month: "Optional — month created, for finer sorting.",
  status: "Draft hides it from the shop · Available shows it · Reserved / Sold mark it accordingly.",
  price: "Set a price; leave both blank for \"price on request\".",
  medium: "Materials used — shown on the piece page.",
  dimensions: "The piece's size — shown on the piece page.",
  description: "A short story or note about the piece.",
  images: "Drag in photos. The first is the main image; reorder with the arrows.",
  imageMove: "Reorder or remove this photo.",
  shipping: "Packing size/weight — only needed later if shipping automation is switched on.",
  save: "Save this piece.",
  cancel: "Discard changes and go back.",
  replyEmail: "Opens your email app to reply to this lead.",
  closeInquiry: "Mark this inquiry handled so it drops off your active list.",
  recordSale: "Log a completed sale — marks the piece Sold and adds it to revenue.",
  chooseWork: "Pick the piece that sold.",
  customer: "Links the buyer — matches an existing customer by email, or creates one.",
  finalAmount: "What the piece actually sold for.",
  saleDate: "When it sold — you can backdate it.",
  channel: "Where the sale came from (Instagram, referral, gallery…).",
  notes: "Private notes about the sale, just for you.",
  shippingSale: "Optionally record the delivery address and tracking.",
  addCustomer: "Create a customer record by hand.",
  saveCustomer: "Save this customer's details.",
  edit: "Update this customer's details.",
  kind: "Blocked = you're unavailable · Open = a bookable window (used only if self-booking is on).",
  dateRange: "The date and time range to block or open.",
  repeat: "Make it recurring — e.g. every weekend, until a chosen date.",
  saveAvailability: "Save this availability rule.",
  reset: "Clear the form.",
  consultation: "Log a meeting with a client.",
  mode: "How the consultation happens.",
  location: "The meeting link or address.",
  deleteBlock: "Edit or remove this availability block.",
  invite: "Send an email invite — they set their own password and get access. No passwords to share.",
  role: "Their access level. Owner/developer/admin can manage users; staff cannot.",
  sendInvite: "Send the invitation email.",
  removeUser: "Remove this person's access — deletes their Studio login.",
  revenue: "Your sales totals, grouped so you can see what's working.",
  repeatBuyer: "The share of customers who've bought more than once.",
  averageTicket: "The typical amount a piece sells for.",
  customerLtv: "How often each customer buys, and their total value over time.",
  payments: "Turns on online checkout. Needs a payment provider set up first. Off = you record sales manually.",
  shippingAutomation: "Enables carrier rates and labels. Needs carrier accounts. Off = you arrange shipping manually.",
  selfBooking: "Lets customers book consultations from your site, using your \"Open\" availability windows.",
  calendarSync: "Two-way Google Calendar sync. Needs you to connect your Google account.",
  forgotPassword: "Emails you a link to set a new password.",
  password: "Choose a password to finish setting up your account.",
  systemsDiagnose: "Run AI triage on this error group. One diagnosis is cached per group — use Re-run to force a fresh pass.",
  systemsExecute: "Disabled in observation mode. When enabled, opens a PR with the proposed fix and runs tests before merge.",
  systemsRollback: "Re-promote the last known-good production deployment. Reverts code, not the database.",
  systemsReview: "Rate the AI's proposed fix vs. what you'd actually do — tracks agreement before Execute is enabled.",
  systemsStatus: "Lifecycle state of this error group.",
  systemsRefresh: "Reload the latest error groups and counts.",
  notesAdd: "Add a private notes page for a fresh thought stream.",
  notesRename: "Rename this page inline — press Enter or click away to save.",
  notesDelete: "Delete this page. Your last remaining page is always kept.",
  notesBoardToggle: "Open the shared team board once the Studio has more than one member.",
  notesBoardDelete: "Delete this team-board note. You can remove your own posts; managers can remove any post.",
  boardComposer: "Write a note for everyone in the Studio team board.",
  postBoard: "Publish this note to the shared team board.",
} as const;

export type StudioHintId = keyof typeof studioHints;
