export const studioHints = {
  wordmark: "Back to your Studio overview.",
  navCatalogue: "Add, edit, and arrange your artworks — these are the pieces shown in your public shop.",
  navLandingPage: "Edit the public Collections, Exhibitions, Press, and Gallery sections while keeping their visual layouts safe.",
  navInquiries: "Messages from people interested in a specific piece or a commission.",
  navSales: "Record a sale to mark a piece sold and build your revenue history.",
  navCustomers: "Everyone who's bought or enquired, with their history in one place.",
  navScheduling: "Block off dates you're unavailable and log consultations.",
  navUsers: "Invite teammates and control who can access the Studio.",
  navInsights: "See public page visits and inquiry activity over time.",
  navSettings: "Switch on upgrade features (payments, booking) when you're ready.",
  viewSite: "Open your public website to see what visitors see.",
  signOut: "Securely log out of the Studio.",
  userRole: "You're signed in here — the tag shows your access level.",
  tips: "Turn these little hints on or off anytime.",
  addWork: "Start a new piece — add its photos, details, and price.",
  statusFilters: "Show or hide pieces by status. Drafts are only visible here, never in the shop.",
  catalogueSearch: "Find a piece by title, series, slug, medium, or year.",
  clearSearch: "Clear the catalogue search.",
  seriesFilter: "Show only pieces assigned to this collection.",
  quickAdd: "Rapidly create several placeholder pieces to flesh out later.",
  bulkStatus: "Change the status of every selected piece at once.",
  bulkSeries: "Move all selected pieces into a collection.",
  createSeries: "Create a new collection and assign it to every selected piece.",
  applyBulk: "Apply the chosen bulk change to your selected pieces.",
  applyDetails: "Apply the filled-in details to every selected piece. Blank fields stay unchanged.",
  selectAll: "Select or clear every piece currently shown by the search and filters.",
  saveSelected: "Save the edited names and prices for the selected pieces.",
  rowStatus: "Change this piece's catalogue status immediately.",
  viewWork: "Open this piece to edit its details or photos.",
  title: "The name of the piece (required).",
  slug: "The piece's web address — auto-fills from the title; edit only if you want.",
  year: "Year created (required) — used to group your catalogue.",
  series: "Put the piece in a collection, or type a new name to create one on the spot.",
  month: "Optional — month created, for finer sorting.",
  status: "Draft hides it from the shop · Available shows it · Reserved / Sold mark it accordingly.",
  price: "Set a price; leave both blank for \"price on request\".",
  medium: "Materials used — shown on the piece page.",
  dimensions: "The piece's size — shown on the piece page.",
  description: "A short story or note about the piece.",
  images: "Drag in photos. The first is the main image; reorder with the arrows.",
  imageMove: "Reorder or remove this photo.",
  shipping: "Packing size/weight — only needed later if shipping automation is switched on.",
  save: "Save this piece.",
  cancel: "Discard changes and go back.",
  replyEmail: "Opens your email app to reply to this lead.",
  closeInquiry: "Mark this inquiry handled so it drops off your active list.",
  archiveInquiry: "Hide this inquiry from the active inbox while keeping it stored in your records.",
  restoreInquiry: "Return this inquiry to the active Studio inbox.",
  inquiryArchive: "Open inquiries that have been archived from the active inbox.",
  recordSale: "Log a completed sale — marks the piece Sold and adds it to revenue.",
  chooseWork: "Pick the piece that sold.",
  customer: "Links the buyer — matches an existing customer by email, or creates one.",
  finalAmount: "What the piece actually sold for.",
  saleDate: "When it sold — you can backdate it.",
  channel: "Where the sale came from (Instagram, referral, gallery…).",
  notes: "Private notes about the sale, just for you.",
  shippingSale: "Optionally record the delivery address and tracking.",
  addCustomer: "Create a customer record by hand.",
  saveCustomer: "Save this customer's details.",
  edit: "Update this customer's details.",
  kind: "Blocked = you're unavailable · Open = a bookable window (used only if self-booking is on).",
  dateRange: "The date and time range to block or open.",
  repeat: "Make it recurring — e.g. every weekend, until a chosen date.",
  saveAvailability: "Save this availability rule.",
  reset: "Clear the form.",
  consultation: "Log a meeting with a client.",
  mode: "How the consultation happens.",
  location: "The meeting link or address.",
  deleteBlock: "Edit or remove this availability block.",
  invite: "Send an email invite — they set their own password and get access. No passwords to share.",
  role: "Their access level. Owner/developer/admin can manage users; staff cannot.",
  sendInvite: "Send the invitation email.",
  removeUser: "Remove this person's access — deletes their Studio login.",
  revenue: "Your sales totals, grouped so you can see what's working.",
  repeatBuyer: "The share of customers who've bought more than once.",
  averageTicket: "The typical amount a piece sells for.",
  insightPeriod: "Switch between daily, weekly, and monthly traffic and inquiry trends.",
  insightViews: "Every public page load in the selected period. One person opening five pages counts as five views. Studio pages, and visits by you and the AVINTPH team, are excluded.",
  insightVisitors: "How many people visited, not how many pages they opened. One person viewing five pages is 1 visitor and 5 views. This is a daily figure only — visitors cannot be totalled across a week or month, because the same person is counted fresh each day by design.",
  insightInquiries: "Public inquiries received in the selected period, counted from the inquiry records.",
  insightConversion: "Inquiries per 100 visits. This shows whether attention is turning into interest.",
  insightTrends: "Compare activity across the selected period. Daily unique visitors are only shown for daily buckets.",
  insightTopPages: "The public pages receiving the most visits in the selected period.",
  customerLtv: "How often each customer buys, and their total value over time.",
  payments: "Turns on online checkout. Needs a payment provider set up first. Off = you record sales manually.",
  shippingAutomation: "Enables carrier rates and labels. Needs carrier accounts. Off = you arrange shipping manually.",
  selfBooking: "Lets customers book consultations from your site, using your \"Open\" availability windows.",
  calendarSync: "Two-way Google Calendar sync. Needs you to connect your Google account.",
  forgotPassword: "Emails you a link to set a new password.",
  password: "Choose a password to finish setting up your account.",
  notesAdd: "Add a private notes page for a fresh thought stream.",
  notesRename: "Rename this page inline — press Enter or click away to save.",
  notesDelete: "Delete this page. Your last remaining page is always kept.",
  notesBoardToggle: "Open the shared team board once the Studio has more than one member.",
  notesBoardDelete: "Delete this team-board note. You can remove your own posts; managers can remove any post.",
  boardComposer: "Write a note for everyone in the Studio team board.",
  postBoard: "Publish this note to the shared team board.",
  landingPublish: "Show or hide this whole section on the public home page.",
  landingEyebrow: "Small supporting label shown above the section title.",
  landingTitle: "The main heading for this public section.",
  landingDescription: "Optional supporting copy shown beneath the section heading.",
  landingSaveSection: "Save this section's public copy and visibility.",
  landingAddItem: "Add another entry within this section's safe limit.",
  landingReorder: "Move this entry earlier or later in the section.",
  landingRemove: "Remove this entry from the public landing page.",
  landingFormat: "Choose whether this press entry is an image feature or text link.",
  landingItemEyebrow: "Small label shown above this entry's title.",
  landingItemTitle: "The title shown for this landing-page entry.",
  landingItemSubtitle: "Supporting metadata shown beneath the entry title.",
  landingItemCopy: "The longer copy shown with this entry.",
  landingSource: "Credit or publication source shown with this entry.",
  landingLinkUrl: "Optional link opened from this entry.",
  landingLinkLabel: "Text used for the entry's link.",
  landingItemPublish: "Show or hide this entry on the public page.",
  landingSaveItem: "Save this entry's copy, links, and media.",
  landingImage: "Upload an image for this landing-page entry.",
  landingImageLabel: "Caption shown with this image on the public page.",
  landingAltText: "Describe this image for visitors using assistive technology.",
  inquirySearch: "Search names, emails, messages, and work titles.",
  inquiryView: "Switch between active, archived, and all inquiries.",
  inquiryType: "Show only piece inquiries or commission inquiries.",
  inquiryStatus: "Show inquiries with a specific workflow status.",
  inquirySort: "Toggle between newest-first and oldest-first.",
  inquiryClear: "Reset every inquiry filter and return to the active view.",
  inquiryOpen: "Open the full inquiry and its available actions.",
  inquiryRestore: "Restore this archived inquiry to the active inbox.",
  salesCustomer: "Match this sale to an existing customer or create one by email.",
  customerName: "The buyer's name for this sale.",
  customerEmail: "The buyer's email for receipts and records.",
  customerPhone: "Optional contact number for this buyer.",
  currency: "Currency used for the recorded sale amount.",
  originatingInquiry: "Link this sale to the inquiry that led to it.",
  shipment: "Add optional carrier and delivery tracking details.",
  carrier: "The carrier handling this delivery.",
  tracking: "The shipment tracking number.",
  package: "How the artwork is packaged for delivery.",
  orderStatus: "Update this order's fulfilment status.",
  availabilityHeading: "Create or edit the dates shown in your studio calendar.",
  availabilityDate: "The date range covered by this availability rule.",
  availabilityTime: "The time range, unless this is an all-day rule.",
  allDay: "Treat this rule as covering the full day.",
  availabilityReason: "Private note explaining why this time is blocked or open.",
  resetAvailability: "Discard the current availability edits.",
  appointmentCustomer: "Optional customer linked to this consultation.",
  appointmentInquiry: "Optional inquiry linked to this consultation.",
  appointmentTitle: "The name shown for this consultation.",
  appointmentDateTime: "When the consultation starts and ends.",
  appointmentStatus: "The current status of this consultation.",
  saveAppointment: "Record this consultation in the studio calendar.",
  editAvailability: "Load this calendar rule into the form for editing.",
  deleteAvailability: "Delete this availability rule from the calendar.",
  updateAppointment: "Update the consultation's status.",
  loginEmail: "Your Studio account email.",
  loginPassword: "Your Studio account password.",
  signIn: "Sign in to the Chroma Fairy Studio.",
  backToSite: "Return to the public Chroma Fairy website.",
  resetEmail: "The account email to send a password-reset link to.",
  sendReset: "Send a secure password-reset link if the account exists.",
  backToLogin: "Return to the Studio sign-in page.",
  settingsGroup: "Feature switches related to this Studio area.",
  deleteSelected: "Delete the selected draft works that have no sales history.",
  batchDetails: "Apply only the filled catalogue details to every selected work.",
  inlineDetails: "Edit the selected works' public titles and prices together.",
  selectWork: "Select this work for bulk editing or removal.",
  deleteWork: "Delete this work when it has no sales history.",
  workFlags: "Set the visibility and merchandising flags for this work.",
  shippingFields: "Optional packed dimensions used for future shipping workflows.",
  imageUpload: "Add artwork images; the first image becomes the primary image.",
  imagePrimary: "Choose which image represents this work in the catalogue.",
  imageRemove: "Remove this image from the work.",
  notesPage: "Open this private notes page.",
  notesEditor: "Write private notes for the Studio.",
  notesDrawerToggle: "Open or close your private Studio notes.",
  dismissWelcome: "Dismiss this Studio welcome message.",
  mobileMenu: "Open the Studio navigation.",
} as const;

export type StudioHintId = keyof typeof studioHints;
